//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsureGo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimHistory
    {
        public int ClaimId { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public string ClaimStatus { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public int PolicyId { get; internal set; }
    }
}
