//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsureGo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual Policy Policy { get; set; }
        public int? VehicleId { get; internal set; }
        public int? UserId { get; internal set; }
        public int? InsuranceTypeId { get; internal set; }
        public int? PlanId { get; internal set; }
        public int? DurationId { get; internal set; }
    }
}
