//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsureGo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumRate
    {
        public int RateId { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<decimal> BasePremium { get; set; }
        public Nullable<decimal> PerYearCharge { get; set; }
    
        public virtual VehicleType VehicleType { get; set; }
    }
}
