//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTIInsurance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LTIInsuranceDBEntities : DbContext
    {
        public LTIInsuranceDBEntities()
            : base("name=LTIInsuranceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<InsurancePlan> InsurancePlans { get; set; }
        public virtual DbSet<InsuranceType> InsuranceTypes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<PolicyDuration> PolicyDurations { get; set; }
        public virtual DbSet<PremiumRate> PremiumRates { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<ClaimHistory> ClaimHistories { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> CalculatePremium(Nullable<int> vehicleTypeId, Nullable<int> vehicleAge)
        {
            var vehicleTypeIdParameter = vehicleTypeId.HasValue ?
                new ObjectParameter("VehicleTypeId", vehicleTypeId) :
                new ObjectParameter("VehicleTypeId", typeof(int));
    
            var vehicleAgeParameter = vehicleAge.HasValue ?
                new ObjectParameter("VehicleAge", vehicleAge) :
                new ObjectParameter("VehicleAge", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CalculatePremium", vehicleTypeIdParameter, vehicleAgeParameter);
        }
    
        public virtual int RenewPolicy(string oldPolicyNumber)
        {
            var oldPolicyNumberParameter = oldPolicyNumber != null ?
                new ObjectParameter("OldPolicyNumber", oldPolicyNumber) :
                new ObjectParameter("OldPolicyNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RenewPolicy", oldPolicyNumberParameter);
        }
    }
}
